---
title: "Lobster Analysis"
format: html
bibliography: references.bib
---

## Summary

GitHub and R practice using data on abundance, size and fishing pressure of California spiny lobster (Panulirus interruptus) collected along the mainland coast of the Santa Barbara Channel.

## Lobster Abundance

```{r}
#| message: false
#| warning: false
#| echo: false

library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)

lobster_abundance <- read_csv(here::here("data/Lobster_Abundance_All_Years_20220829.csv"))
lobster_abundance <- lobster_abundance %>% 
    mutate(SIZE_MM = na_if(SIZE_MM, -99999))

not_napl<- lobster_abundance%>%
  filter(SITE != "NAPL")

aque_70mm<- lobster_abundance%>%
  filter(SITE == "AQUE" & SIZE_MM >= 70)

# `group_by() %>% summarize()` practice
max_lobster<- lobster_abundance%>%
  group_by(SITE, MONTH)%>%
  summarize(MAX_LENGTH = max(SIZE_MM, na.rm = TRUE))

lobster_size_lrg <- lobster_abundance %>%
    filter(YEAR %in% c(2019, 2020, 2021)) %>%
    mutate(SIZE_BIN = if_else(SIZE_MM <= 70, true = "small", false = "large")) %>%
    group_by(SITE, SIZE_BIN) %>%
    summarize(COUNT = n()) %>%
    drop_na()

ggplot(data=lobster_size_lrg,
       aes(x=SITE, y=COUNT,
           fill= SIZE_BIN))+
  geom_col(position = "dodge")+
  theme_classic()
```

## Lobster Trap Counts

```{r}
#| message: false
#| warning: false
#| echo: false

library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)

lobster_traps <- read_csv(here::here("data/Lobster_Trap_Counts_All_Years_20210519.csv"))

lobster_traps <- lobster_traps %>% 
    mutate(TRAPS = na_if(TRAPS, -99999))

not_napl <- lobster_traps %>% 
    filter(SITE != "NAPL")

carp_20_traps <- lobster_traps %>% 
    filter(SITE == "CARP" & TRAPS > 20)

#Find the maximum number of commercial trap floats using max() and group by SITE and MONTH. Think about how you want to treat the NA values in TRAPS (Hint: check the arguments in max()). Check your output.

max_float_site_by_month <- lobster_traps %>% 
  group_by(SITE, MONTH) %>% 
  summarize(MAX_TRAP= max(TRAPS, na.rm= TRUE)) 

lobsters_traps_summarize <- lobster_traps %>% 
  group_by(SITE, YEAR) %>% 
  summarize(TOTAL_TRAPS = sum(TRAPS, na.rm = TRUE))

lobster_traps_fishing_pressure <- lobster_traps %>% 
    filter(YEAR %in% c(2019, 2020, 2021)) %>%
    mutate(FISHING_PRESSURE = if_else(TRAPS >= 8, true = "high", false = "low")) %>%
    group_by(SITE, FISHING_PRESSURE) %>%
    summarize(COUNT = n()) %>%
    drop_na()
ggplot(data = lobster_traps, aes(x = TRAPS)) +
    geom_histogram() +
    facet_wrap( ~ YEAR)
# bar plot
ggplot(data = lobster_traps_fishing_pressure, aes(x = SITE, y = COUNT, fill = FISHING_PRESSURE)) +
    geom_col()+
  labs(x= "Site", y="Count", fill="Fishing Pressure")+
  theme_bw()
```

## References [@lter2022]
