---
title: "owner-analysis"
format: html
author: Nicole Greco
---

## Exercise: Explore, Clean, and Wrangle Data

```{r}
#| message: false
#| warning: false

library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
```

### Load data
```{r}
#| message: false
#| warning: false
#| 
lobster_abundance <- read_csv(here::here("data/Lobster_Abundance_All_Years_20220829.csv"))
```

### Convert missing values using mutate() and na_if()
```{r}
lobster_abundance <- lobster_abundance %>% 
    mutate(SIZE_MM = na_if(SIZE_MM, -99999))
```

### filter() practice
```{r}
not_napl<- lobster_abundance%>%
  filter(SITE != "NAPL")

aque_70mm<- lobster_abundance%>%
  filter(SITE == "AQUE" & SIZE_MM >= 70)

# `group_by() %>% summarize()` practice
max_lobster<- lobster_abundance%>%
  group_by(SITE, MONTH)%>%
  summarize(MAX_LENGTH = max(SIZE_MM, na.rm = TRUE))
```

## Exercise: Data Visualization

Histogram
```{r}
ggplot(data = lobster_abundance,
       aes(SIZE_MM))+
  geom_histogram()+
  facet_wrap(~SITE)
```

Group Data
```{r}
lobsters_summarize<- lobster_abundance%>%
  group_by(SITE, YEAR)%>%
  summarize(COUNT=n())
```

Line Graph
```{r}
ggplot(data = lobsters_summarize,
       aes(x=YEAR, y=COUNT))+
  geom_line(aes(color=SITE))

### Add points to line plot
ggplot(data = lobsters_summarize,
       aes(x=YEAR, y=COUNT))+
  geom_point(aes(color=SITE))+
  geom_line(aes(color=SITE))
```

Bar Graph
```{r}
lobster_size_lrg <- lobster_abundance %>%
    filter(YEAR %in% c(2019, 2020, 2021)) %>%
    mutate(SIZE_BIN = if_else(SIZE_MM <= 70, true = "small", false = "large")) %>%
    group_by(SITE, SIZE_BIN) %>%
    summarize(COUNT = n()) %>%
    drop_na()

ggplot(data=lobster_size_lrg,
       aes(x=SITE, y=COUNT,
           fill= SIZE_BIN))+
  geom_col()

ggplot(data=lobster_size_lrg,
       aes(x=SITE, y=COUNT,
           fill= SIZE_BIN))+
  geom_col(position = "dodge")+
  theme_classic()
```

Save plot
```{r}
ggsave(here::here("figs", "lobster_size.jpg"), width = 12, height=12)
```

